"""create sku unique

Revision ID: c1a22c630924
Revises: 4116533afa71
Create Date: 2026-05-19 13:14:28.455185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a22c630924'
down_revision: Union[str, Sequence[str], None] = '4116533afa71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_noon_product_sku'), 'noon_product', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noon_product_sku'), table_name='noon_product')
    # ### end Alembic commands ###
