"""create initial migration file

Revision ID: da5f7ab2989d
Revises: 
Create Date: 2026-05-19 10:59:33.518703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5f7ab2989d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noon_brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noon_brand_id'), 'noon_brand', ['id'], unique=False)
    op.create_table('noon_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.Text(), nullable=False),
    sa.Column('subCategoryId', sa.Integer(), nullable=False),
    sa.Column('subCategoryName', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noon_category_id'), 'noon_category', ['id'], unique=False)
    op.create_table('noon_merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noon_merchant_id'), 'noon_merchant', ['id'], unique=False)
    op.create_table('noon_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brandId', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('imageUrl', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.Text(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('subCategoryId', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_noon_product_id'), 'noon_product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noon_product_id'), table_name='noon_product')
    op.drop_table('noon_product')
    op.drop_index(op.f('ix_noon_merchant_id'), table_name='noon_merchant')
    op.drop_table('noon_merchant')
    op.drop_index(op.f('ix_noon_category_id'), table_name='noon_category')
    op.drop_table('noon_category')
    op.drop_index(op.f('ix_noon_brand_id'), table_name='noon_brand')
    op.drop_table('noon_brand')
    # ### end Alembic commands ###
